### ISSUE TITLE
Exception when exporting Winston config

### ISSUE THREAD

**Issue by Patrick-Remy** [nestjs-community/nestjs-config#69]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**nestjs-config version**
1.2.9

**@nestjs/common+core or other package versions**
 - @nestjs/common: 5.6.2
 - @nestjs/core: 5.6.2

#### Excepted behavior 
Not throwing an exception

#### Actual behavior or outcome (for issue)
I am using `nest-config` with `nest-winston`, but it seems that `new transports.Console()` is crashing the ConfigService.

#### Replication/Example
*winston.options.ts*
```typescript
import { TransformableInfo } from 'logform'
import { format, LoggerOptions, transports } from 'winston'

const printFormat = (info: TransformableInfo) => {
  return `${info.timestamp} ${info.level}: ${info.message}`
}

const options: LoggerOptions = {
  transports: [
    new transports.Console()
  ]
}

export default options
```

custom *LoggerModule.ts*
```typescript
import { WinstonModule } from 'nest-winston'
import { ConfigService } from 'nestjs-config'

export const LoggerModule = WinstonModule.forRootAsync(
  {
    useFactory: (configService: ConfigService) => {
      const options = configService.get('winston.options')
      console.log(options)
      return options
    },
    inject: [ConfigService]
  }
)
```

*[ExceptionHandler] Cannot convert undefined or null to object*
```
TypeError: Cannot convert undefined or null to object
     at Function.keys (<anonymous>)
     at Object.bindCustomHelpers (/usr/src/app/node_modules/nestjs-config/dist/module/config.service.js:226:23)
     at Object.keys.reduce (/usr/src/app/node_modules/nestjs-config/dist/module/config.service.js:233:46)
     at Array.reduce (<anonymous>)
     at Object.bindCustomHelpers (/usr/src/app/node_modules/nestjs-config/dist/module/config.service.js:226:36)
     at Object.keys.reduce (/usr/src/app/node_modules/nestjs-config/dist/module/config.service.js:233:46)
     at Array.reduce (<anonymous>)
     at Object.bindCustomHelpers (/usr/src/app/node_modules/nestjs-config/dist/module/config.service.js:226:36)
     at Object.keys.reduce (/usr/src/app/node_modules/nestjs-config/dist/module/config.service.js:233:46)
     at Array.reduce (<anonymous>)
     at Object.bindCustomHelpers (/usr/src/app/node_modules/nestjs-config/dist/module/config.service.js:226:36)
     at Object.keys.reduce (/usr/src/app/node_modules/nestjs-config/dist/module/config.service.js:233:46)
     at Array.reduce (<anonymous>)
     at Object.bindCustomHelpers (/usr/src/app/node_modules/nestjs-config/dist/module/config.service.js:226:36)
     at Object.keys.reduce (/usr/src/app/node_modules/nestjs-config/dist/module/config.service.js:233:46)
     at Array.reduce (<anonymous>)
```

**Comment by bashleigh** [comment]
this should be fixed in the next release. However the bindConfigHelpers method will still add methods from that 'object' class to the helper methods which probably isn't desired. follow #72 for progress on this
